### ISSUE TITLE
vcf unit tests broken in python 3 (?)

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#164]
Do other people get this or is my installation messed up?

```
(py3)[tim@Tims-MacBook ~/sinai/git/varcode]$ nosetests test/test_vcf.py
/Users/tim/venvs/py3/lib/python3.4/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
...........................E
======================================================================
ERROR: test.test_vcf.test_sample_info_genotype
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tim/venvs/py3/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/tim/sinai/git/varcode/test/test_vcf.py", line 145, in test_sample_info_genotype
    eq_(variants.metadata[variants[0]]['sample_info']['metastasis']['GT'],
KeyError: 'sample_info'

----------------------------------------------------------------------
Ran 28 tests in 0.809s

FAILED (errors=1)
(py3)[tim@Tims-MacBook ~/sinai/git/varco

**Comment by timodonnell** [comment]
Setting up a fresh venv seemed to fix this, closing.
