### ISSUE TITLE
Too many open files on error on getting top effect

### ISSUE THREAD

**Issue by arahuja** [hammerlab/varcode#62]
```
In [91]:
len(variant_collection)
Out[91]:
82655
```
```
vc_effect = [v.top_effect() for v in variant_collection]
```
gives 
```
Traceback (most recent call last):
  File "/Users/arahuja/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 970, in get_records
  File "/Users/arahuja/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 233, in wrapped
  File "/Users/arahuja/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 267, in _fixed_getinnerframes
  File "/Users/arahuja/anaconda/lib/python2.7/inspect.py", line 1044, in getinnerframes
  File "/Users/arahuja/anaconda/lib/python2.7/inspect.py", line 1004, in getframeinfo
  File "/Users/arahuja/anaconda/lib/python2.7/inspect.py", line 454, in getsourcefile
  File "/Users/arahuja/anaconda/lib/python2.7/inspect.py", line 483, in getmodule
  File "/Users/arahuja/anaconda/lib/python2.7/inspect.py", line 467, in getabsfile
  File "/Users/arahuja/anaconda/lib/python2.7/posixpath.py", line 371, in abspath
OSError: [Errno 24] Too many open files
```

```
INFO:root:Cached file Homo_sapiens.GRCh37.75.gtf from URL ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz
INFO:root:Cached file Homo_sapiens.GRCh37.75.cdna.all.fa from URL ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.75.cdna.all.fa.gz
```
messages printed ~2000 times.

I'm pretty sure this is due to how I constructed my `VariantCollection`

```
variant_collection = VariantCollection([Variant(contig = row['Chrom'], 
                                                start=row['Pos'], 
                                                ref=row['Ref'],
                                                alt = row['Alt'].split(',')[0],
                                                ensembl=EnsemblRelease(75))
                                            for i, row in snv_data.iterrows()])
```
vs
```
ensembl = EnsemblRelease(75)
variant_collection = VariantCollection([Variant(contig = row['Chrom'], 
                                                start=row['Pos'], 
                                                ref=row['Ref'],
                                                alt = row['Alt'].split(',')[0],
                                                ensembl=ensembl)
                                            for i, row in snv_data.iterrows()])
```

This is mostly just user error, but perhaps there is a way to make this simpler.

**Comment by iskandr** [comment]
Yeah, every EnsemblRelease holds on to a bunch of file/database handles. I guess after a few thousand things go awry. 

What do you think of me adding `pyensembl.ensembl_grch37` and `pyensembl.ensembl_grch38` to alleviate needing to specify/construct specific versions of `EnsemblRelease`?

**Comment by arahuja** [comment]
Yea I think that works.  Maybe even going so far as just specifying the number in `Variant`  the user doesn't need to learn the PyEnsembl interface when working with Varcode

**Comment by iskandr** [comment]
OK, added prebuilt EnsemblRelease objects to `pyensembl` via https://github.com/hammerlab/pyensembl/pull/86. 

I was thinking of having each `Variant` only know about its reference genome (since that's less surprising and hides PyEnsembl from the user) but pretty much every method of a `Variant` ends up using the reference annotations.
