### ISSUE TITLE
Varcode requires pandas >= 0.13.1, however it uses 0.15 functionality #12

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varcode#92]
When reading in a MAF:

```
Traceback (most recent call last):
  File "/Users/tavi/.virtualenvs/utopia/bin/topiary", line 99, in <module>
    main()
  File "/Users/tavi/.virtualenvs/utopia/bin/topiary", line 59, in main
    variants = variant_collection_from_args(args)
  File "/Users/tavi/.virtualenvs/utopia/lib/python2.7/site-packages/topiary/args.py", line 61, in variant_collection_from_args
    variant_collections.append(varcode.load_maf(maf_path))
  File "/Users/tavi/.virtualenvs/utopia/lib/python2.7/site-packages/varcode/maf.py", line 96, in load_maf
    maf_df = load_maf_dataframe(path)
  File "/Users/tavi/.virtualenvs/utopia/lib/python2.7/site-packages/varcode/maf.py", line 69, in load_maf_dataframe
    header=0)
TypeError: parser_f() got an unexpected keyword argument 'skip_blank_lines'
```

See: http://stackoverflow.com/questions/29129192/skip-blank-lines-not-working-with-pandas

Apparently `skip_blank_lines` wasn't introduced until 0.15.0.

Also see https://github.com/hammerlab/topiary/issues/12

**Comment by iskandr** [comment]
Fixed by https://github.com/hammerlab/varcode/pull/99
